### ISSUE TITLE
Retry pri HTTP 502

### ISSUE THREAD

**Issue by ErikZigo** [keboola/provisioning-client#17]
Klient resi backoff pouze pro HTTP 503 a dalsi kody ignoruje.

https://github.com/keboola/provisioning-client/blob/49632f502ec6868c47acbb864bea0042e659225a/src/Keboola/Provisioning/Client.php#L86

Nekdy se ale muze stat, ze load balancer v AWS vrati HTTP 502/504. Klient pak vyhodi vyjimku s chybou `Error receiving response from Provisioning API`

Stacilo by dodelat backoff i pro ty dalsi kody

**Comment by ondrejhlavacek** [comment]
@ErikZigo kde se to stalo? problém je, že jde o sync api cally, takže tam backoffy moc dlouho běžet nemůžou.

**Comment by ErikZigo** [comment]
@ondrejhlavacek  `transformation-60460913502504ca05fff014ecf45690`

**Comment by ErikZigo** [comment]
Tomu moc nerozumim. Ted je tam backoff na 10 pokusu a http 503 + curl chyby.
Tak kdyz se tam prida i na 502 + 504 tak to nicemu nevadi ne?

**Comment by ondrejhlavacek** [comment]
máš pravdu, je to klient! jsem hlava dubová :-) už jsem to tady přepisoval, aby se retries dělaly, ale rychleji, ale klient fakt může pohodlně počkat
